version: '3.8'

services:
  grace-dashboard:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: 
